name: Django DevSecOps CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, feature-testing]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit safety

      - name: Run Django unit tests
        env:
          DJANGO_SETTINGS_MODULE: django_ledger_project.settings
        run: python manage.py test

      - name: Static code analysis (Bandit)
        run: bandit -r ledger

      - name: Dependency vulnerability scan (Safety)
        run: safety check --full-report

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/web-ledger:${{ github.sha }} .

      - name: Scan Docker image (Trivy)
        uses: aquasecurity/trivy-action@v0.19.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/web-ledger:${{ github.sha }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/web-ledger:${{ github.sha }}
